baseurl: "/"
permalink: pretty
title: "leme"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

logo:
  logo_desktop_image: assets/images/logo/leme-logo-mono.svg
  logo_mobile_image: assets/images/logo/leme-logo-free.svg
  logo_desktop_text: "Leme by Leander Jansen"
  logo_mobile_text: ""
  logo_desktop_height: "30px"
  logo_desktop_width: "200px"
  logo_mobile_height: "20px"
  logo_mobile_width: "150px"

seo:
  meta_twitter_site: "@leanderrj"
  meta_og_image: "https://www.zerostatic.io/theme/jekyll-atlantic/jekyll-atlantic-screenshot.png"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate

paginate: 3
paginate_path: /projects/page:num/

collections:
  posts:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
